name: juno
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Core workflow
  - nextflow>=23.04.0
  - python>=3.6
  
  # Bioinformatics tools
  - fastq-scan=1.0.1
  - trimmomatic=0.40
  - bbmap=39.34
  - fastp=0.24.0
  - bwa=0.7.18
  - samtools=1.21
  - ivar=1.4.3
  - kraken2=2.1.3
  - krakentools
  - spades=4.0.0
  - blast=2.15.0
  - pilon=1.24
  - quast=5.3.0
  - multiqc=1.25
