# Input/Output paths
input_dir: "/path/to/fastq"
output_dir: "/path/to/juno_output"

# Assembly strategy selection
assembly_mode: "reference"  # Options: "reference" or "denovo"

# Kraken2 database path
kraken2_db: "/path/to/kraken2_db"

# Skip human read removal using NCBI's SRA human read removal tool (HRRT)
skip_hrrt: false
