# Input/Output paths
input_dir: "/path/to/fastq"
output_dir: "/path/to/output_dir"

# References path, default reference directory, DO NOT change.
refs_dir: "${projectDir}/references"

# Database path
kraken2_db: "/path/to/kraken2_db"

# Resource configuration, default number of threads per process
threads: 32

# Human scrubber processing option, set to true for HPC environments
parallel_hrrt: false

# Quality control thresholds
qc_thresholds:
    min_coverage: 90
    min_depth: 15
